### ISSUE TITLE
영타일때 문장연습의 한 문장이 너무 깁니다

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [suhdonghwi/OpenTyping#2]
![image](https://user-images.githubusercontent.com/16515307/46841241-bf9fa500-ce01-11e8-828a-2845064e80ae.png)

문장연습을 할 때 진짜 한 문장을 모두 입력하게 하는 것은 무리가 있어 보입니다.

![image](https://user-images.githubusercontent.com/16515307/46841276-e362eb00-ce01-11e8-88c7-e599e8d33f2a.png)

긴글연습처럼 길이에 따라 끊는 것이 조금 더 나아 보입니다.

**Comment by suhdonghwi** [comment]
흠.. 사실 원래 그렇게 하려고 했는데 그러면 문장연습이 긴글연습하고 차별화 되는 부분이 거의 없어져서 냅뒀습니다.

문장연습에서 한 문장이 지나치게 긴 것은 학습 데이터에서 문장을 적절히 끊어서 처리하도록 하였습니다. 그래서 제가 어느정도 끊어준게 저 정도인데 지금 보니 좀 길긴 하네요..

**Comment by suhdonghwi** [comment]
기본 포함된 연습 데이터의 문장 길이를 끊어서 조금 줄여놓았습니다.

**Comment by suhdonghwi** [comment]
말씀 해주신대로 짧은 글 연습도 긴글 연습 처럼 길이에 따라서 자르는게 나아보이네요. 문장 중간 중간을 끊어 놓았더니 긴글 연습에서 굉장히 어색하게 보이는 문제가 발생했습니다.
