### ISSUE TITLE
자리 연습에 소문자 모드가 있으면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [suhdonghwi/OpenTyping#3]
Shift 를 사용하지 않아도 되는 모드가 있었으면 합니다.

자리 연습을 하고 싶지 Shift 키 잘 누르는 연습을 하고 싶은 것이 아니라서 ...

**Comment by suhdonghwi** [comment]
오! 그걸 생각 못했네요. 빠르게 구현하겠습니다.
