### ISSUE TITLE
문장 연습에서 평균 타속이 나왔으면 좋겠습니다.

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [suhdonghwi/OpenTyping#4]
![image](https://user-images.githubusercontent.com/16515307/46841513-5c167700-ce03-11e8-986f-2717ba24901b.png)

현재에는 마지막으로 입력한 타속만 나오지만 
문장 연습을 시작하여 입력한 총 평균타속이 나오면 좋을 것 같습니다.

**Comment by suhdonghwi** [comment]
동의합니다. 이것도 빠르게 추가하겠습니다.
